name: basenji
channels:
  - defaults
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - astropy
  - cython
  - h5py
  - intervaltree
  - joblib
  - matplotlib
  - natsort
  - networkx
  - numpy
  - packaging
  - pandas
  - pillow
  - pybedtools
  - pybigwig
  - python=3.10
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tabulate
